# in progress
- hosts: localhost
  tasks:
    # install packages
    - name: install packages
      become: true
      package:
        name: 
          # add packages
        state: present

    # change gnome default settings
