# in progress
- hosts: localhost
  tasks:
    # install packages
    - name: install packages
      become: true
      package:
        name: 
          - tlp
          - tlp-rdw
          - wireguard-tools
        state: present

    # change gnome default settings
    - name: scaling factor
      dconf:
        key: "org/gnome/desktop/interface/text-scaling-factor"
        value: 1.25

    - name: blank screen
      dconf:
        key: "/org/gnome/desktop/session/idle-delay"
        value: "uint32 120"

    - name: mouse click emulation
      dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/click-method"
        value: "fingers"
